baseURL = "https://thibautjombart.netlify.com/"
languageCode = "en-us"
title = "Thibaut Jombart website"
theme = "hugo-initio"
publishDir = "public"

[params]
name = "Thibaut Jombart"
description = "Lecturer in Outbreak Analytics"
email = "thibautjombart@gmail.com"
phone = "0044 (0)20 7594 3658"
address = "Department of Infectious Disease Epidemiology, Faculty of Medicine, Imperial College London, London W2 1PG, UK"
year = 2017
background = ""
favicon = "images/gt_favicon.png"
DateForm = "December 22, 2017"

showSubheader = true
showServices = false
showRecentWorks = false
showDownload = false
showClients = false

footerEnableFollowme = true
footerEnableContact = true
footerEnableTextWidget = false
footerEnableFormWidget = false
footerEnableCopyrightWidget = true


[[menu.main]]
name = "home"
url = "/"
weight = 1

[[menu.main]]
name = "blog"
url = "/post/"
weight = 5

# [params.disqus]
#     site = "hugo-initio-site.disqus.com"

# [params.sharethis]
#     property = "123456789012345678901234"
#     custom = true

# [params.google.analytics]
#     trackerID = "GA-000000000-0"


[[params.social]]
title = "email"
url = "mailto:thibautjombart@gmail.com"
icon = "fa-envelope"
footer = true
sharethis = true
network = "email"

[[params.social]]
title = "twitter"
url = "https://twitter.com/TeebzR"
icon = "fa-twitter-square"
footer = true
sharethis = true
network = "twitter"

[[params.social]]
title = "github"
url = "https://github.com/thibautjombart"
icon = "fa-github"
footer = true
sharethis = true
network = ""

[[params.social]]
title = "facebook"
url = "https://www.facebook.com/thibaut.jombart"
icon = "fa-facebook-square"
footer = true
sharethis = true
network = "facebook"

# [[params.social]]
# title = "instagram"
# url = "https://www.instagram.com/nickname"
# icon = "fa-instagram"
# footer = true
# sharethis = false
# network = ""

# [[params.social]]
# title = "google+"
# url = "https://plus.google.com/+nickname"
# icon = "fa-google-plus-square"
# footer = false
# sharethis = true
# network = "googleplus"

# [[params.social]]
# title = "linkedin"
# url = "https://www.linkedin.com/in/nickname"
# icon = "fa-linkedin-square"
# footer = false
# sharethis = true
# network = "linkedin"

# [[params.social]]
# title = "tumblr"
# url = "https://nickname.tumblr.com"
# icon = "fa-tumblr-square"
# footer = false
# sharethis = false
# network = "tumblr"
